### ISSUE TITLE
Not able to start dirigible-che-editor-plugin

### ISSUE THREAD

**Issue by skabashnyuk** [dirigiblelabs/dirigible-che-editor-plugin#2]
I'm testing new demos https://github.com/che-incubator/che-demos/pull/5 of Eclipse Che capability to swap IDE. At this moment I'm not able to run  dirigible-che-editor-plugin
![Знімок екрана  о 11 27 24](https://user-images.githubusercontent.com/1614429/56566443-52907780-65bb-11e9-8e6d-f10e6a464c1b.png)

**Comment by skabashnyuk** [comment]
log
https://gist.github.com/skabashnyuk/33de768e5672e461ea4d83a82cf691b0

I see two issues:
```
07:54:41,393 |-INFO in ch.qos.logback.core.FileAppender[FILE_CORE] - File property is set to [../logs/dirigible-core-2019-04-23.log]
07:54:41,395 |-ERROR in ch.qos.logback.core.FileAppender[FILE_CORE] - Failed to create parent directories for [/usr/local/tomcat/../logs/dirigible-core-2019-04-23.log]
07:54:41,396 |-ERROR in ch.qos.logback.core.FileAppender[FILE_CORE] - openFile(../logs/dirigible-core-2019-04-23.log,true) call failed. java.io.FileNotFoundException: ../logs/dirigible-core-2019-04-23.log (No such file or directory)
	at java.io.FileNotFoundException: ../logs/dirigible-core-2019-04-23.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
```
and
```
19-04-23 07:55:00.510 [INFO ] [DirigibleClusteredScheduler_Worker-6] o.e.d.c.e.s.ExtensionsSynchronizer - Synchronized a new Extension [template-job/template.js] for Extension Point [ide-template] from location: /template-job/template.extension
2019-04-23 07:55:00.511 [INFO ] [DirigibleClusteredScheduler_Worker-6] o.e.d.c.e.s.ExtensionsSynchronizer - Synchronized a new Extension [ide-repository/services/repository-view.js] for Extension Point [ide-view] from location: /ide-repository/extensions/repository-view.extension
2019-04-23 07:55:00.512 [INFO ] [DirigibleClusteredScheduler_Worker-6] o.e.d.c.e.s.ExtensionsSynchronizer - Synchronized a new Extension [ide/services/menu/help] for Extension Point [ide-terminal-menu] from location: /ide-terminal/extensions/menu/help.extension
2019-04-23 07:55:02.592 [ERROR] [http-nio-8080-exec-2] o.e.d.e.j.s.JavascriptEngineRestService - No Javascript Engine registered
org.eclipse.dirigible.commons.api.scripting.ScriptingException: No Javascript Engine registered
	at org.eclipse.dirigible.engine.js.processor.DefaultJavascriptEngineExecutor.executeServiceModule(DefaultJavascriptEngineExecutor.java:63) ~[dirigible-engine-javascript-3.4.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.engine.js.processor.JavascriptEngineProcessor.executeService(JavascriptEngineProcessor.java:42) ~[dirigible-engine-javascript-3.4.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.engine.js.service.JavascriptEngineRestService.executeJavascriptServiceGet(JavascriptEngineRestService.java:71) ~[dirigible-engine-javascript-3.4.0-SNAPSHOT.jar:na]
```

**Comment by ThuF** [comment]
Hi Sergii,

I couldn't reproduce the issue, from the log it seems more like something related to the initial bootstrap (as the instance is not fully ready). We had similar issue https://github.com/eclipse/dirigible/issues/383, but it was fixed few months ago.

Maybe you were using old instance? Can you try to create and start a new workspace with the "dirigible-che-editor-plugin" plugin? At least this works for me ...

Regards,
Yordan

**Comment by skabashnyuk** [comment]
not able to reproduce it anymore.
